title: Tim Harrington
email: t.harrington@gwmail.gwu.edu
description: Professional Website & Engineering Portfolio
baseurl: ""
url: "https://TimHarrington10.github.io"
theme: minima
markdown: kramdown
header_pages:
  - index.md
  - yacht.md
  - thetatau.md
  - solidworks.md
